---
title: "Лабораторная работа № 3"
  format:
    md:
      output-file: README.md
---

# Развертывание системы мониторинга ELK Stack

## Цель работы

1.  Освоить базовые подходы централизованного сбора и накопления информации

2.  Освоить современные инструменты развертывания контейнирозованных приложений

3.  Закрепить знания о современных сетевых протоколах прикладного уровня

## Ход выполнения практической работы

### Шаг 1. Развернуть систему мониторинга на базе ElasticSearch

1.  Увеличиваем размер виртуальной памяти системы



2.  Далее следуем инструкции по ссылке:

https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html

Создаём файл docker-compose.yml, а так же конфигурационные файлы для каждого модуля:

```         
filebeat.yml
packetbeat.yml
```

3.  После формирования файлов с конфигурациями, запускаем образы

4.  Переходим на `localhost:5061` и авторизируемся



Шаг 2. Работа с ElasticSearch

1.  Проверям, что установленны все средства для сбора информации из файлов журналов и сбора аналитики трафика



2.  Создаем новый data view для filebeat



3.  Создаем новый data view для packetbeat



## Оценка результата

Была развёрнута система ElasticSearch и настроена система сбора трафика и лог-файлов.

## Вывод

В результате работы была освоена система контейнеризации приложений Docker, работа с Docker-compose и освоена система централизованного сбора и накопления информации ElasticSearch.
